name: Check Google Service Account Credentials

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  test-google-credentials:
    runs-on: ubuntu-latest

    steps:
    # Checkout your repository
    - name: Checkout code
      uses: actions/checkout@v2

    # Create the credentials file from secret
    - name: Create credentials file
      run: |
        echo "${{ secrets.GOOGLE_SHEET_CREDENTIALS }}" > /home/runner/service_account_credentials.json

    # Display the contents of the file for debugging
    - name: Show credentials file
      run: cat /home/runner/service_account_credentials.json

    # Validate the presence of 'private_key' field and correct formatting using jq
    - name: Validate private key formatting
      run: |
        PRIVATE_KEY=$(jq -r '.private_key' /home/runner/service_account_credentials.json)
        if [[ $PRIVATE_KEY == *"-----BEGIN PRIVATE KEY-----"* ]]; then
          echo "Private key is correctly formatted."
        else
          echo "Private key formatting issue!" && exit 1
        fi

    # Validate the file structure using jq
    - name: Validate JSON structure
      run: |
        cat /home/runner/service_account_credentials.json | jq .
