name: Test Google Service Account

on:
  push:
    branches:
      - main
  workflow_dispatch: # Allows manually triggering the workflow

jobs:
  check-google-service-account:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout code
        uses: actions/checkout@v3

      # Set up Google Cloud SDK
      - name: Set up Google Cloud SDK
        uses: google-github-actions/setup-gcloud@v1
        with:
          version: 'latest'

      # Authenticate with Google Cloud using the service account JSON
      - name: Authenticate to Google Cloud
        env:
          GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SHEET_CREDENTIALS }}
        run: |
          # Save the secret to a JSON file
          echo "$GOOGLE_CREDENTIALS" > "$HOME/gcloud-service-key.json"

          # Validate the JSON format using jq
          echo "Validating JSON format..."
          cat "$HOME/gcloud-service-key.json" | jq .

          # Authenticate with the service account
          echo "Authenticating with Google Cloud..."
          gcloud auth activate-service-account --key-file="$HOME/gcloud-service-key.json"

          # List authenticated accounts to verify
          gcloud auth list

      # Verify access by listing available Google Cloud projects (example check)
      - name: Verify Service Account Permissions
        run: gcloud projects list