name: Python application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pandas openpyxl

    # Install Chrome browser
    - name: Install Chrome
      run: |
        sudo apt-get update
        sudo apt-get install -y wget unzip
        wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
        sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y
        google-chrome --version

    # Install matching ChromeDriver based on the installed Chrome version
    - name: Install ChromeDriver
      run: |
        # Extract the major version of Chrome (more reliable method)
        CHROME_VERSION=$(google-chrome --version | grep -oP '\d+\.\d+\.\d+\.\d+' | cut -d '.' -f 1)
        echo "Installed Chrome version: $CHROME_VERSION"
        
        # Fetch the correct ChromeDriver version
        DRIVER_VERSION=$(curl -s "https://chromedriver.storage.googleapis.com/LATEST_RELEASE_$CHROME_VERSION")
        
        if [ -z "$DRIVER_VERSION" ]; then
          echo "Failed to retrieve ChromeDriver version for Chrome version $CHROME_VERSION"
          exit 1
        fi
        
        echo "Downloading ChromeDriver version: $DRIVER_VERSION"
        wget -N https://chromedriver.storage.googleapis.com/$DRIVER_VERSION/chromedriver_linux64.zip
        unzip chromedriver_linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        chromedriver --version

    # Run your Python script
    - name: Run the Python script
      run: |
        python sis_school_enrollment.py
