name: Test Secret

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Create credentials file
      run: |
        if [ -z "${{ secrets.GOOGLE_SHEET_CREDENTIALS }}" ]; then
          echo "The environment variable GOOGLE_SHEET_CREDENTIALS is not set or is empty."
          exit 1
        fi
        echo "${{ secrets.GOOGLE_SHEET_CREDENTIALS }}" | base64 --decode > /home/runner/service_account_credentials.json
        cat /home/runner/service_account_credentials.json

    - name: Check file
      run: |
        ls -la /home/runner/
        cat /home/runner/service_account_credentials.json
