name: Python application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Python
      uses: actions/setup-python@v2
      with:
        python-version: '3.x'

    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install selenium pandas openpyxl

    # Check if Chrome is installed and install if necessary
    - name: Check and Install Chrome
      run: |
        if ! command -v google-chrome &> /dev/null; then
          echo "Chrome not found, installing..."
          sudo apt-get update
          sudo apt-get install -y wget unzip
          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
          sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y
          google-chrome --version
        else
          echo "Chrome is already installed."
        fi

    # Use a static ChromeDriver version
    - name: Install static ChromeDriver
      run: |
        # Define the static ChromeDriver version
        DRIVER_VERSION="128.0.6613.137"
        DRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/$DRIVER_VERSION/linux64/chromedriver-linux64.zip"

        echo "Downloading ChromeDriver from: $DRIVER_URL"
        wget $DRIVER_URL -O chromedriver-linux64.zip

        if [ ! -f chromedriver-linux64.zip ]; then
          echo "Failed to download ChromeDriver. Exiting."
          exit 1
        fi

        unzip chromedriver-linux64.zip
        sudo mv chromedriver /usr/local/bin/chromedriver
        sudo chmod +x /usr/local/bin/chromedriver
        chromedriver --version

    # Run your Python script
    - name: Run the Python script
      run: |
        python sis_school_enrollment.py
