name: Python application

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository
      - name: Checkout repository
        uses: actions/checkout@v2

      # Set up Python
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: '3.x'

      # Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install selenium pandas openpyxl google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      # Decode and save the Base64-encoded Google credentials
      - name: Decode and Save Google Credentials
        env:
          BASE64_ENCODED_GOOGLE_CREDENTIALS: ${{ secrets.GOOGLE_SHEET_CREDENTIALS }}
        run: |
          echo "Decoding the Base64 secret..."
          echo "$BASE64_ENCODED_GOOGLE_CREDENTIALS" | base64 --decode > "$HOME/service_account_credentials.json"

      # Display and validate the credentials file
      - name: Display and Validate Credentials File
        run: |
          echo "Displaying credentials file..."
          cat "$HOME/service_account_credentials.json"
          echo "Validating JSON format..."
          cat "$HOME/service_account_credentials.json" | jq .

      # Check and install Chrome
      - name: Check and Install Chrome
        run: |
          if ! command -v google-chrome &> /dev/null; then
            echo "Chrome not found, installing..."
            sudo apt-get update
            sudo apt-get install -y wget unzip
            wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
            sudo dpkg -i google-chrome-stable_current_amd64.deb || sudo apt-get install -f -y
            google-chrome --version
          else
            echo "Chrome is already installed."
          fi

      # Install static ChromeDriver
      - name: Install ChromeDriver
        run: |
          DRIVER_VERSION="128.0.6613.137"
          DRIVER_URL="https://storage.googleapis.com/chrome-for-testing-public/$DRIVER_VERSION/linux64/chromedriver-linux64.zip"

          echo "Downloading ChromeDriver from: $DRIVER_URL"
          wget $DRIVER_URL -O chromedriver-linux64.zip

          if [ ! -f chromedriver-linux64.zip ]; then
            echo "Failed to download ChromeDriver. Exiting."
            exit 1
          fi

          unzip chromedriver-linux64.zip
          sudo mv chromedriver-linux64/chromedriver /usr/local/bin/chromedriver
          sudo chmod +x /usr/local/bin/chromedriver
          chromedriver --version

      # Run the Python script
      - name: Run the Python script
        run: |
          python sis_school_enrollment.py

      # List files after script execution
      - name: List files after script execution
        run: |
          ls -la

      # Upload Excel file
      - name: Upload Excel file
        uses: actions/upload-artifact@v3
        with:
          name: school-enrollment-data
          path: '*.xlsx'
