name: Scrape SIS Punjab and Capture Screenshot

on:
  push:
    branches:
      - main  # Replace with your branch name if different
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  scrape-and-screenshot:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.12'

      - name: Install dependencies
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip
          pip install selenium pandas openpyxl google-auth google-auth-oauthlib google-auth-httplib2 google-api-python-client

      - name: Run scraper and capture screenshot
        run: |
          source .venv/bin/activate
          export http_proxy=http://52.67.10.183:80
          export https_proxy=http://52.67.10.183:80
          python sis_school_enrollment.py
          
      - name: Upload screenshot as an artifact
        uses: actions/upload-artifact@v3
        with:
          name: screenshot
          path: screenshot_*.png  # This matches the screenshot file created in the Python script
