name: Check Website Accessibility

on:
  push:
    branches:
      - main

jobs:
  check-accessibility:
    runs-on: ubuntu-latest

    steps:
      - name: Check website accessibility
        id: check_site
        run: |
          # Function to check website accessibility with retries
          check_accessibility() {
            local retries=3
            local count=0
            local timeout=10
            
            while [ $count -lt $retries ]; do
              RESPONSE=$(curl -s -o /dev/null -w "%{http_code}" --max-time $timeout https://sis.punjab.gov.pk/)
              IP_ADDRESS=$(curl -s --max-time $timeout http://api.ipify.org)

              echo "HTTP Response Code: $RESPONSE"
              echo "GitHub Actions IP Address: $IP_ADDRESS"

              if [ "$RESPONSE" -eq 200 ]; then
                echo "Website is accessible."
                return 0
              else
                echo "Attempt $((count + 1)) failed: Website is not accessible. HTTP Response Code: $RESPONSE"
                count=$((count + 1))
                sleep 5  # wait before retrying
              fi
            done
            
            echo "Website is not accessible after $retries attempts."
            exit 1
          }

          # Call the function to check accessibility
          check_accessibility
