name: Test Website Connectivity

on:
  push:
    branches:
      - main
  workflow_dispatch:  # Allows manual trigger of the workflow

jobs:
  test-connectivity:
    runs-on: ubuntu-latest

    steps:
      - name: Test connection with curl
        run: |
          echo "Testing connection to https://sis.punjab.gov.pk/"
          curl -I -k --proxy http://52.67.10.183:80 -I https://sis.punjab.gov.pk/
